baseURL = 'https://blog.lessandro.ugulino.com'
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Lessandro"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© Copyright | Lessandro Ugulino"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Enable dark mode as default
	#darkmode = true

	# Use homepage.md instead of a list of posts
	homepage = false

    # Add a subtitle to your website
	subtitle = "A website containing something I've been working on"

# Custom JavaScript
[params.customjs]
# enable Javascript by setting to true
enabled = false

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
#name = "All Posts"
#url = "/post"
#weight = 2

[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4

[[menu.main]]
#name = "Categories"
#url = "/categories"
#weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/lessandro-ugulino/whoami"

[[params.social]]
name = "Linkedin"
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/lezampieri/"

#[[params.social]]
#name = "Email"
#icon = "fas fa-envelope"
#cmd = "mailto:example@example.com"

#[[params.social]]
#name = "RSS"
#icon = "fas fa-rss"
#url = "/index.xml"
